services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  gym-node:
    image: gym-node
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-end/.env
  
  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  nginx: 
    container_name: gym_nginx
    build: ./nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - gym-node
      - react

volumes:
  postgres-volume:
  react-volume: